### ISSUE TITLE
Reenable resource shrinking

### ISSUE THREAD

**Issue by laurentpellegrino** [medicalid/issues#134]
Release builds are produced with some resources that are empty. This is due to a bug with the resource shrinking option:

https://issuetracker.google.com/issues/38411240 

An error example:

> Caused by: android.content.res.Resources$NotFoundException: File res/color/abc_primary_text_material_light.xml from color state list resource ID #0x7f1001aa
> 	at android.content.res.Resources.loadColorStateList(Resources.java:2255)
> 	at android.content.res.TypedArray.getColorStateList(TypedArray.java:343)
> 	at android.widget.TextView.<init>(TextView.java:681)
> 	at android.support.v7.widget.AppCompatTextView.<init>(Unknown Source)
> 	at android.support.v7.widget.AppCompatTextView.<init>(Unknown Source)
> 	at android.support.v7.app.AppCompatDelegateImplV9.a(Unknown Source)
> 	at android.support.v4.view.j$a.onCreateView(Unknown Source)
> 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
> 	... 24 more

The feature must be reenabled as soon as the bug is fixed.

**Comment by laurentpellegrino** [comment]
Also, Proguard optimizations need to be restored:

> proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
