### ISSUE TITLE
Bad notification posted from package app.medicalid.free

### ISSUE THREAD

**Issue by laurentpellegrino** [medicalid/issues#25]
Issue appears on LG devices with stock ROM only!

> android.app.RemoteServiceException: Bad notification posted from package app.medicalid.free: Couldn't expand RemoteViews for: StatusBarNotification(pkg=app.medicalid.free user=UserHandle{0} id=7 tag=null score=20 key=0|app.medicalid.free|7|null|10122: Notification(pri=2 contentView=app.medicalid.free/0x7f040048 vibrate=null sound=null defaults=0x0 flags=0xa color=0xfffe0038 category=status vis=PUBLIC))
>   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1519)
>   at android.os.Handler.dispatchMessage(Handler.java:102)
>   at android.os.Looper.loop(Looper.java:148)
>   at android.app.ActivityThread.main(ActivityThread.java:5551)
>   at java.lang.reflect.Method.invoke(Native Method)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
>   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

It affects free and paid versions.

**Comment by laurentpellegrino** [comment]
I was able to reproduce. The notification makes use of a custom notification layout. The layout that is loaded depends of the Android version. To differentiate layouts, alternative resources are used:
- res/layout-v21/mylayout.xml
- res/layout-v24/mylayout.xml

Even when API is version 23, LG ROM is loaded layout from _layout-v24_. 

A solution is to put all layouts in the classic _layout_ folder and to differentiate the one to load programatically.
